name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Run flake8
        run: flake8 .

      - name: Run script
        run: python script.py

      - name: Run tests and save results
        run: |
          pytest test_eg.py > result.log

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: result.log
